#ifndef INCLUDE_KEYBOARD_H
#define INCLUDE_KEYBOARD_H

#include <stdint.h>

enum {
	KEYBOARD_KEY_A = 0x00,
    KEYBOARD_KEY_B,
    KEYBOARD_KEY_C,
    KEYBOARD_KEY_D,
    KEYBOARD_KEY_E,
    KEYBOARD_KEY_F,
    KEYBOARD_KEY_G,
    KEYBOARD_KEY_H,
    KEYBOARD_KEY_I,
    KEYBOARD_KEY_J,
    KEYBOARD_KEY_K,
    KEYBOARD_KEY_L,
    KEYBOARD_KEY_M,
    KEYBOARD_KEY_N,
    KEYBOARD_KEY_O,
    KEYBOARD_KEY_P,
    KEYBOARD_KEY_Q,
    KEYBOARD_KEY_R,
    KEYBOARD_KEY_S,
    KEYBOARD_KEY_T,
    KEYBOARD_KEY_U,
    KEYBOARD_KEY_V,
    KEYBOARD_KEY_W,
    KEYBOARD_KEY_X,
    KEYBOARD_KEY_Y,
    KEYBOARD_KEY_Z,
    KEYBOARD_KEY_1,
    KEYBOARD_KEY_2,
    KEYBOARD_KEY_3,
    KEYBOARD_KEY_4,
    KEYBOARD_KEY_5,
    KEYBOARD_KEY_6,
    KEYBOARD_KEY_7,
    KEYBOARD_KEY_8,
    KEYBOARD_KEY_9,
    KEYBOARD_KEY_0,

    KEYBOARD_KEY_ENTER,
    KEYBOARD_KEY_ESC,
    KEYBOARD_KEY_BACKSPACE,
    KEYBOARD_KEY_TAB,
    KEYBOARD_KEY_SPACE,
    KEYBOARD_KEY_GRAVE,
    KEYBOARD_KEY_HYPEN,
    KEYBOARD_KEY_EQUALS,
    KEYBOARD_KEY_OPEN_BRACKET,
    KEYBOARD_KEY_CLOSE_BRACKET,
    KEYBOARD_KEY_BACKSLASH,
    KEYBOARD_KEY_SEMICOLON,
    KEYBOARD_KEY_APOSTROPHE,
    KEYBOARD_KEY_COMMA,
    KEYBOARD_KEY_FULL_STOP,
    KEYBOARD_KEY_SLASH,
	//KEYBOARD_KEY_HASH,

    KEYBOARD_KEY_NUM_SLASH,
    KEYBOARD_KEY_NUM_STAR,
    KEYBOARD_KEY_NUM_MINUS,
    KEYBOARD_KEY_NUM_PLUS,
    KEYBOARD_KEY_NUM_ENTER,
    KEYBOARD_KEY_NUM_1,
    KEYBOARD_KEY_NUM_2,
    KEYBOARD_KEY_NUM_3,
    KEYBOARD_KEY_NUM_4,
    KEYBOARD_KEY_NUM_5,
    KEYBOARD_KEY_NUM_6,
    KEYBOARD_KEY_NUM_7,
    KEYBOARD_KEY_NUM_8,
    KEYBOARD_KEY_NUM_9,
    KEYBOARD_KEY_NUM_0,
    KEYBOARD_KEY_NUM_FULL_STOP,
	
	KEYBOARD_KEY_ARROW_UP,
	KEYBOARD_KEY_ARROW_LEFT,
	KEYBOARD_KEY_ARROW_DOWN,
	KEYBOARD_KEY_ARROW_RIGHT,
	
	KEYBOARD_KEY_INSERT,
	KEYBOARD_KEY_HOME,
	KEYBOARD_KEY_PAGE_UP,
	KEYBOARD_KEY_DELETE,
	KEYBOARD_KEY_END,
	KEYBOARD_KEY_PAGE_DOWN,

    KEYBOARD_KEY_F1,
    KEYBOARD_KEY_F2,
    KEYBOARD_KEY_F3,
    KEYBOARD_KEY_F4,
    KEYBOARD_KEY_F5,
    KEYBOARD_KEY_F6,
    KEYBOARD_KEY_F7,
    KEYBOARD_KEY_F8,
    KEYBOARD_KEY_F9,
    KEYBOARD_KEY_F10,
    KEYBOARD_KEY_F11,
    KEYBOARD_KEY_F12,

    KEYBOARD_KEY_NUM_LOCK,
    KEYBOARD_KEY_CAPS_LOCK,
    KEYBOARD_KEY_SCROLL_LOCK,

    KEYBOARD_KEY_LEFT_CTRL,
    KEYBOARD_KEY_LEFT_SHIFT,
    KEYBOARD_KEY_LEFT_ALT,
    KEYBOARD_KEY_RIGHT_CTRL,
    KEYBOARD_KEY_RIGHT_SHIFT,
    KEYBOARD_KEY_RIGHT_ALT,
    KEYBOARD_KEY_SYSREQ,
	
	// Extended codes
	KEYBOARD_KEY_MULTIMEDIA_PREVIOUS,
	KEYBOARD_KEY_MULTIMEDIA_NEXT,
	KEYBOARD_KEY_MULTIMEDIA_MUTE,
	KEYBOARD_KEY_MULTIMEDIA_CALCULATOR,
	KEYBOARD_KEY_MULTIMEDIA_PLAY,
	KEYBOARD_KEY_MULTIMEDIA_STOP,
	KEYBOARD_KEY_MULTIMEDIA_VOL_DOWN,
	KEYBOARD_KEY_MULTIMEDIA_VOL_UP,
	
	KEYBOARD_KEY_LEFT_GUI,
	KEYBOARD_KEY_RIGHT_GUI,
	KEYBOARD_KEY_APPS,
	
	KEYBOARD_KEY_POWER,
	KEYBOARD_KEY_SLEEP,
	KEYBOARD_KEY_WAKE,
	
	KEYBOARD_KEY_MULTIMEDIA_WWW_HOME,
	KEYBOARD_KEY_MULTIMEDIA_WWW_SEARCH,
	KEYBOARD_KEY_MULTIMEDIA_WWW_FAVORITES,
	KEYBOARD_KEY_MULTIMEDIA_WWW_REFRESH,
	KEYBOARD_KEY_MULTIMEDIA_WWW_STOP,
	KEYBOARD_KEY_MULTIMEDIA_WWW_FORWARD,
	KEYBOARD_KEY_MULTIMEDIA_WWW_BACK,
	
	KEYBOARD_KEY_MULTIMEDIA_MY_COMPUTER,
	KEYBOARD_KEY_MULTIMEDIA_EMAIL,
	KEYBOARD_KEY_MULTIMEDIA_MEDIA_SELECT,

	KEYBOARD_KEY_UNKNOWN
};

// PS/2 commands
#define PS2_DATA_PORT		0x60
#define PS2_COMMAND_PORT	0x64

#define PS2_STATUS_INPUT_BUFFER_FULL	0x02

// Keyboard commands
#define KEYBOARD_SET_LED	0xED

// Response Codes
#define KEYBOARD_ACK		0xFA
#define KEYBOARD_RESEND		0xFE

/*
#define KEYBOARD_KEY_NULL					0x00

#define KEYBOARD_KEY_SOH					0x01
#define KEYBOARD_KEY_STX					0x02
#define KEYBOARD_KEY_ETX					0x03
#define KEYBOARD_KEY_EOT					0x04
#define KEYBOARD_KEY_ENQ					0x05
#define KEYBOARD_KEY_ACK					0x06
#define KEYBOARD_KEY_BEL					0x07

#define KEYBOARD_KEY_BACKSPACE				0x08
#define KEYBOARD_KEY_TAB					0x09
#define KEYBOARD_KEY_LINE_FEED				0x0A

#define KEYBOARD_KEY_VTAB					0x0B
#define KEYBOARD_KEY_FORM_FEED				0x0C

#define KEYBOARD_KEY_CARRIAGE_RETURN		0x0D

#define KEYBOARD_KEY_SO						0x0E
#define KEYBOARD_KEY_SI						0x0F
	
#define KEYBOARD_KEY_DLE					0x10
#define KEYBOARD_KEY_DC1					0x11
#define KEYBOARD_KEY_DC2					0x12
#define KEYBOARD_KEY_DC3					0x13
#define KEYBOARD_KEY_DC4					0x14
#define KEYBOARD_KEY_NAK					0x15
#define KEYBOARD_KEY_SYN					0x16
#define KEYBOARD_KEY_ETB					0x17
#define KEYBOARD_KEY_CAN					0x18
#define KEYBOARD_KEY_EM						0x19
#define KEYBOARD_KEY_SUB					0x1A
#define KEYBOARD_KEY_ESC					0x1B
#define KEYBOARD_KEY_FS						0x1C
#define KEYBOARD_KEY_GS						0x1D
#define KEYBOARD_KEY_RS						0x1E
#define KEYBOARD_KEY_US						0x1F

#define KEYBOARD_KEY_SPACE					0x20
#define KEYBOARD_KEY_EXCLAMATION_MARK		0x21
#define KEYBOARD_KEY_QUOTATION_MARK			0x22
#define KEYBOARD_KEY_HASH					0x23
#define KEYBOARD_KEY_DOLLAR					0x24
#define KEYBOARD_KEY_PERCENT				0x25
#define KEYBOARD_KEY_AMPERSAND				0x26
#define KEYBOARD_KEY_APOSTROPHE				0x27
#define KEYBOARD_KEY_OPEN_ROUND_BRACKET		0x28
#define KEYBOARD_KEY_CLOSE_ROUND_BRACKET	0x29
#define KEYBOARD_KEY_ASTERISK				0x2A
#define KEYBOARD_KEY_PLUS					0x2B
#define KEYBOARD_KEY_COMMA					0x2C
#define KEYBOARD_KEY_MINUS					0x2D
#define KEYBOARD_KEY_FULL_STOP				0x2E
#define KEYBOARD_KEY_SLASH					0x2F

#define KEYBOARD_KEY_0						0x30
#define KEYBOARD_KEY_1						0x31
#define KEYBOARD_KEY_2						0x32
#define KEYBOARD_KEY_3						0x33
#define KEYBOARD_KEY_4						0x34
#define KEYBOARD_KEY_5						0x35
#define KEYBOARD_KEY_6						0x36
#define KEYBOARD_KEY_7						0x37
#define KEYBOARD_KEY_8						0x38
#define KEYBOARD_KEY_9						0x39
#define KEYBOARD_KEY_COLON					0x3A
#define KEYBOARD_KEY_SEMICOLON				0x3B
#define KEYBOARD_KEY_OPEN_ANGLE_BRACKET		0x3C
#define KEYBOARD_KEY_EQUALS					0x3D
#define KEYBOARD_KEY_CLOST_ANGLE_BRACKET	0x3E
#define KEYBOARD_KEY_QUESTION_MARK			0x3F

#define KEYBOARD_KEY_AT_SIGN				0x40
#define KEYBOARD_KEY_A_UPPER				0x41
#define KEYBOARD_KEY_B_UPPER				0x42
#define KEYBOARD_KEY_C_UPPER				0x43
#define KEYBOARD_KEY_D_UPPER				0x44
#define KEYBOARD_KEY_E_UPPER				0x45
#define KEYBOARD_KEY_F_UPPER				0x46
#define KEYBOARD_KEY_G_UPPER				0x47
#define KEYBOARD_KEY_H_UPPER				0x48
#define KEYBOARD_KEY_I_UPPER				0x49
#define KEYBOARD_KEY_J_UPPER				0x4A
#define KEYBOARD_KEY_K_UPPER				0x4B
#define KEYBOARD_KEY_L_UPPER				0x4C
#define KEYBOARD_KEY_M_UPPER				0x4D
#define KEYBOARD_KEY_N_UPPER				0x4E
#define KEYBOARD_KEY_O_UPPER				0x4F

#define KEYBOARD_KEY_P_UPPER				0x50
#define KEYBOARD_KEY_Q_UPPER				0x51
#define KEYBOARD_KEY_R_UPPER				0x52
#define KEYBOARD_KEY_S_UPPER				0x53
#define KEYBOARD_KEY_T_UPPER				0x54
#define KEYBOARD_KEY_U_UPPER				0x55
#define KEYBOARD_KEY_V_UPPER				0x56
#define KEYBOARD_KEY_W_UPPER				0x57
#define KEYBOARD_KEY_X_UPPER				0x58
#define KEYBOARD_KEY_Y_UPPER				0x59
#define KEYBOARD_KEY_Z_UPPER				0x5A
#define KEYBOARD_KEY_OPEN_SQUARE_BRACKET	0x5B
#define KEYBOARD_KEY_BACKSLASH				0x5C
#define KEYBOARD_KEY_CLOSE_SQUARE_BRACKET	0x5D
#define KEYBOARD_KEY_CARET					0x5E
#define KEYBOARD_KEY_UNDERSCORE				0x5F

#define KEYBOARD_KEY_GRAVE					0x60
#define KEYBOARD_KEY_A_LOWER				0x61
#define KEYBOARD_KEY_B_LOWER				0x62
#define KEYBOARD_KEY_C_LOWER				0x63
#define KEYBOARD_KEY_D_LOWER				0x64
#define KEYBOARD_KEY_E_LOWER				0x65
#define KEYBOARD_KEY_F_LOWER				0x66
#define KEYBOARD_KEY_G_LOWER				0x67
#define KEYBOARD_KEY_H_LOWER				0x68
#define KEYBOARD_KEY_I_LOWER				0x69
#define KEYBOARD_KEY_J_LOWER				0x6A
#define KEYBOARD_KEY_K_LOWER				0x6B
#define KEYBOARD_KEY_L_LOWER				0x6C
#define KEYBOARD_KEY_M_LOWER				0x6D
#define KEYBOARD_KEY_N_LOWER				0x6E
#define KEYBOARD_KEY_O_LOWER				0x6F

#define KEYBOARD_KEY_P_LOWER				0x70
#define KEYBOARD_KEY_Q_LOWER				0x71
#define KEYBOARD_KEY_R_LOWER				0x72
#define KEYBOARD_KEY_S_LOWER				0x73
#define KEYBOARD_KEY_T_LOWER				0x74
#define KEYBOARD_KEY_U_LOWER				0x75
#define KEYBOARD_KEY_V_LOWER				0x76
#define KEYBOARD_KEY_W_LOWER				0x77
#define KEYBOARD_KEY_X_LOWER				0x78
#define KEYBOARD_KEY_Y_LOWER				0x79
#define KEYBOARD_KEY_Z_LOWER				0x7A
#define KEYBOARD_KEY_OPEN_CURLY_BRACKET		0x7B
#define KEYBOARD_KEY_VERTICAL_BAR			0x7C
#define KEYBOARD_KEY_CLOSE_CURLY_BRACKET	0x7D
#define KEYBOARD_KEY_TILDE					0x7E
#define KEYBOARD_KEY_DEL					0x7F
*/
void keyboard_init();
unsigned char get_last_key_press();
char key_to_ascii(unsigned char key);

#endif /* INCLUDE_KEYBOARD_H */